### PR TITLE
br-ext: embed opensc for pkcs11-tool

### PR DESCRIPTION
**Pull request by etienne-lms**
Embed opensc package for pkcs11-tool to play with the PKCS11 TA.
(edited: updated to latest series)

Examples of using pkcs11-tool with PKCS11 TA:
(default pkcs11 provider module /usr/lib/libckteec.so)

```
# Get tokens/slots info
pkcs11-tool  --show-info
pkcs11-tool  --list-token-slots
pkcs11-tool  --list-mechanisms

# Initialize token and user PIN
pkcs11-tool --init-token --label test-token --so-pin 1234567890
pkcs11-tool --label test-token --login --so-pin 1234567890 \
            --init-pin --pin ABCDEFGHIJ

# Generate a 2048bit RSA key
pkcs11-tool --token-label test-token --pin ABCDEFGHIJ \
            --keypairgen --key-type RSA:2048 --id 123 --label foo-key

# List token object
pkcs11-tool --token-label test-token --list-objects \
```
Co-developed-by: Gábor Székely <szvgabor@gmail.com>
Signed-off-by: Gábor Székely <szvgabor@gmail.com>
Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
Is it possible to configure the tool use use `/usr/lib/libckteec.so` as the default module? It's not likely that there will be any other module available in our small repo builds.

**Comment by etienne-lms** [comment]
okay i'll look at that.

I did not expect this to be merged, this was rather to share the setup but maybe it's worth integrating this in the optee release.

**Comment by etienne-lms** [comment]
> Is it possible to configure the tool use use /usr/lib/libckteec.so as the default module?

Done. Thank for the suggestion :+1:

**Comment by jenswi-linaro** [comment]
Does it take long to build?

**Comment by etienne-lms** [comment]
This adds 2 packages to the build  pcps-lite and open-sc packages to the build.
Few numbers to compare, on my host, excluding package dwl, with ccache enabled (w/o ccache maybe time x 3).

30min to build the BR original part (before patch) (`rm -rf ../out-br/build && make buildroot`)
1min to add this opensc (`make buildroot  BR2_PACKAGE_OPENSC=y`)
It takes me ~30sec to rebuild only our BR optee_* packages (`rm -rf ../out-br/build/optee_* && make buildroot`).

**Comment by jenswi-linaro** [comment]
Thanks for the investigation. Looks good to me.
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
tag applied

**Pull request merged**
