### PR TITLE
toolchain.mk: Update legacy toolchain download url

### PR DESCRIPTION
**Pull request by vchong**
Fixes https://github.com/OP-TEE/optee_os/issues/1195.

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`
`Tested-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Tags added and ready for merge. Thanks!

**Comment by jbech-linaro** [comment]
Maybe we should try build UEFI stuff again now to see whether it has progressed or not, eventually we don't need the legacy toolchain anymore. Also related to that, I started to play with gcc6.x a little bit more than a month ago (https://github.com/jbech-linaro/optee_os/tree/gcc6).

**Comment by vchong** [comment]
@jbech-linaro FYI HiKey's UEFI fork still does not support gcc5. Ref: https://github.com/Linaro/documentation/pull/7

**Comment by jbech-linaro** [comment]
Alright, then we still need this "legacy" toolchain, thanks for the fix!

**Comment by ryankumar** [comment]
1st i got error in make toolchains but i copied toolchains from one of my friends optee/toolchains. but now i am getting error in make -j2. the Error is in out-br/busybox/ " archival/libarchive/decompress_unlzma.o
/tmp/ccrStxLU.s: Assembler messages:
/tmp/ccrStxLU.s:153: Error: unknown mnemonic rorw' --rorw $8,w0'
/tmp/ccrStxLU.s:614: Error: unknown mnemonic rorw' --rorw $8,w1'
scripts/Makefile.build:197: recipe for target 'archival/lzop.o' failed
make[4]: *** [archival/lzop.o] Error 1
Makefile:743: recipe for target 'archival' failed
make[3]: *** [archival] Error 2
make[3]: *** Waiting for unfinished jobs....

AR archival/libarchive/lib.a
package/pkg-generic.mk:221: recipe for target '/home/mahannee/Qemuv-7/out-br/build/busybox-1.28.3/.stamp_built' failed
make[2]: *** [/home/mahannee/Qemuv-7/out-br/build/busybox-1.28.3/.stamp_built] Error 2
Makefile:16: recipe for target '_all' failed
make[1]: *** [_all] Error 2
make[1]: Leaving directory '/home/mahannee/Qemuv-7/out-br'
common.mk:198: recipe for target 'buildroot' failed
make: *** [buildroot] Error 2 "

any suggestion for this.

**Comment by jforissier** [comment]
@ryankumar you question has nothing to do here. Please open a new issue if you still have not resolved your problem.

**Comment by ryankumar** [comment]
i am trying to resolv this one from last 15days. but i don't know during "make -j2" it's showing same error every time...my procedure is 
1. repo sync
2.cd build/
3. make toolchains : 1st i got error to build toolchains. so i took toolchains from my another system where optee is running properly.
4. make -j2 : the above error is comming in this stage. 

so please suggest me how can i resolve this.

**Comment by ryankumar** [comment]
@jforissier i have another doubt is  that we are using "op.params[0].value.a"  ,what is the memory allocation for this operation and where (in which memory) does it store the data .

Thanks for your quick reply.

**Pull request merged**
