### PR TITLE
Buildroot: add openssl

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jforissier** [comment]
About "print TA being built": isn't `$(MAKE) -C ...` supposed to print a message "Entering directory..."?

**Comment by jenswi-linaro** [comment]
I guess it depends on some flag, currently it's not printed.

**Comment by jforissier** [comment]
OK, don't bother. Thanks.

**Pull request merged**
