### PR TITLE
GCC 8

### PR DESCRIPTION
**Pull request by jforissier**
GCC 8 support.

### CODE REVIEW

**Comment by jforissier** [comment]
Depends on:
- https://github.com/OP-TEE/optee_client/pull/128 (which may be merged independently of this)
- https://github.com/OP-TEE/manifest/pull/120 (which should be merged at the same time as this PR)

**Comment by jforissier** [comment]
Rebased on top of master for convenience (pick a couple of fixes)

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Update: "poplar: avoid compile errors when building Linux with GCC 8.x".

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Ping for "Use GCC 8".

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro good, thanks

**Pull request merged**
