### PR TITLE
hikey960: build using buildroot

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

Depends on https://github.com/OP-TEE/manifest/pull/108

This has only been test compiled, not run on hardware.
@jforissier, would you mind giving it a try?

### CODE REVIEW

**Comment by jforissier** [comment]
> @jforissier, would you mind giving it a try?

Sure. It could take some time however, because I need to clone the whole setup and I have a slow network access here.

**Comment by jforissier** [comment]
First of all, https://github.com/OP-TEE/build/pull/251 and https://github.com/OP-TEE/manifest/pull/109 are needed or `make flash` fails.
With that, the board boots up to kernel initialization but then no login prompt is shown. The console keeps saying "can't open /dev/ttyAMA0: No such file or directory".

**Comment by jenswi-linaro** [comment]
Please test again with the added patch

**Comment by jforissier** [comment]
`Tested-by: Jerome Forissier <jerome.forissier@linaro.org> (HiKey960)`

**Comment by jforissier** [comment]
And also...
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Pull request merged**
