### PR TITLE
Update Links to readthedocs.io

### PR DESCRIPTION
**Pull request by DasBasti**
Links for [build] and [Device specific information] are outdated. replaced URI in README.md

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Thanks! For some reason it seems like readthedocs have added the `/en/` part to all URLs automatically. This is not the first PR catching that, but I'm quite sure that there should be many more.

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by etienne-lms** [comment]
Looks like all materials were in place to finalize...

**Comment by jbech-linaro** [comment]
Indeed, just needed the SB tag and my RB tag to the commit message (re-open the PR).

**Pull request closed without merging**
