### PR TITLE
Xen tools version check

### PR DESCRIPTION
**Pull request by jforissier**
A patch to check that Xen and Xen tools have compatible version numbers, plus a minor cleanup.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@ruchi393 is there a reason why we don't use Xen built from Buildroot instead? That would avoid a need for such a consistency check.

**Comment by ruchi393** [comment]
> @ruchi393 is there a reason why we don't use Xen built from Buildroot instead? That would avoid a need for such a consistency check.

Sorry, I totally missed this query.  
OP-TEE support in xen is currently experimental which needs to be enabled in config options when building xen. That is not available with xen built with buuildroot. That is the reason why we need to keep the xen build separate from Buildroot.

**Comment by ruchi393** [comment]
`Acked-by: Ruchika Gupta <ruchika.gupta@linaro.org>`

**Pull request merged**
