### PR TITLE
qemu_v8: Introducing PAUTH option

### PR DESCRIPTION
**Pull request by ruchi393**
Introduces option PAUTH, which can be used to enable
Pointer Authentication for TA's.

Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

### CODE REVIEW

**Review by jbech-linaro — COMMENTED** [review]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by ruchi393** [comment]
Thanks. Tags applied

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by ruchi393** [comment]
PR updated with tags

**Pull request merged**
