### PR TITLE
buildroot: Update toolchain and kernel headers

### PR DESCRIPTION
**Pull request by jbech-linaro**
The BR2_KERNEL_HEADERS_4_10 has been depracted, so when trying to build
with GDBSERVER=y we got this warning:

  Makefile.legacy:9: *** "You have legacy configuration in your .config!
  Please check your configuration.".  Stop.

To better match recent toolchain updates in this git (gcc updates and
kernel header updates), we also update buildroot to use and provide a
GCC8.x based toolchain as well as 4.19 kernel headers.

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v7)

### CODE REVIEW

**Comment by jforissier** [comment]
Could be good to cite the commit(s) with 12-digit hash etc., But anyway:
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
@jforissier Reviewed-by: Jerome Forissier <jerome@forissier.org> here too?

**Comment by jforissier** [comment]
@jbech-linaro yup.

**Comment by jbech-linaro** [comment]
Commit id added to the commit message.
Squashed, rebased and tag(s) applied (should be) ready for merge! Thanks!

**Pull request merged**
