### PR TITLE
Secure Data Path test setup (SWG-208/209)

### PR DESCRIPTION
**Pull request by etienne-lms**
QEMU configs: enable linux kernel ION, ION_DUMMY and ION "unmapped heap" support/test.

Statically define an "unmapped" heap in ion dummy driver for test on vexpress-qemu.
This part could be removed from the patch: vexpress-qemu linux can get ION "unmaped" heap from the DT.

Depends on https://github.com/linaro-swg/linux/pull/35.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@etienne-lms it looks like this is ready to be merged? Can you rebase and apply the R-b tag?

**Comment by etienne-lms** [comment]
No, we can't merge this. It depends on https://github.com/linaro-swg/linux/pull/35 which defines some of the kernel config directives enabled here.
Moreover, the default "SDP heap location" set here will be used for vexpress-qemu_armv8  but will not fit qemu_armv8 memory layout.

**Comment by jforissier** [comment]
OK thanks.

**Comment by etienne-lms** [comment]
rebased, updated. still depends on  https://github.com/linaro-swg/linux/pull/35.

Locate SDP memory at the top 3Mbytes of the QEMU secure RAM, for both qemu_virt and qemu_armv8.

**Comment by jbech-linaro** [comment]
When, has been merged linaro-swg/linux#35:
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by etienne-lms** [comment]
rebased, with tag applied.

**Pull request merged**
