### PR TITLE
hikey*.mk: Support ptable-linux-8g.img build

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Please note that with this the default ptable is now generated for 8g instead of 4g so those of you still using 4g boards please adjust accordingly!

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Tag added. Thanks!

**Comment by jforissier** [comment]
Merged with slightly modified commit message ("Fixes X" lines re-formatted as "Fixes: X" tags).

**Pull request closed without merging**
