### PR TITLE
juno: download scp version 2.8

### PR DESCRIPTION
**Pull request by jenswi-linaro**
TF-A v2.4 and earlier is used with the SCP binaries provided in the
vexpress-firmware git. With TF-A v2.5 is supposed to use the SCP
binaries released at [1] instead. So update to download the SCP binaries
from [1] instead.

Link [1]: https://downloads.trustedfirmware.org/tf-a/css_scp_2.8.0/juno
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jenswi-linaro** [comment]
Depends on https://github.com/OP-TEE/manifest/pull/189

**Comment by jenswi-linaro** [comment]
Tag applied

**Comment by jenswi-linaro** [comment]
Since OP-TEE/manifest#189 (now merged) depends on this we should merge this soon.

**Comment by jforissier** [comment]
Haha I literally merged 9 seconds after your message we just checked this at the same time :)

**Pull request merged**
