### PR TITLE
hikey: recovery does not need sudo if udev is configured correctly

### PR DESCRIPTION
**Pull request by jforissier**
Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by d3zd3z** [comment]
It shouldn't be necessary to restart udev. It will reread the rules upon new device insertion.

**Comment by jforissier** [comment]
@d3zd3z correct, I'll fix that.

**Comment by d3zd3z** [comment]
Reviewed-by: David Brown <david.brown@linaro.org>

**Comment by jforissier** [comment]
@jenswi-linaro / @jbech-linaro still OK with you?

**Comment by jenswi-linaro** [comment]
Yes, it's OK.

**Comment by jforissier** [comment]
Thanks, tags applied and PR merged.

**Pull request merged**
