### PR TITLE
hikey: Add CONFIG_PINCTRL_SINGLE=y

### PR DESCRIPTION
**Pull request by vchong**
This config is required to prevent errors on boot like below when using
https://github.com/96boards-hikey/linux hikey-mainline-rebase branch:

ssp-pl022 f7106000.spi: could not find pctldev for node /soc/pinmux@f7010000/spi0_pmx_func, deferring probe
gpiochip_add: GPIOs 480..487 (f8014000.gpio) failed to register

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Depends on https://github.com/OP-TEE/manifest/pull/16.

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Looks like a config / DT issue in upstream, no?

**Comment by vchong** [comment]
@jforissier Yes, so this is until they fix/upstream it.

**Comment by jbech-linaro** [comment]
Since the flag is enabled in the default branch at https://github.com/96boards/linux I think we should merge this as of now.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
Makes sense! Victor if you want one more R-b here it is ;-)
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Sure, the more the merrier, but does this break the record for most R-b's in a one-liner PR? :-P
Tags applied. Please merge. Thanks!

**Pull request merged**
