### PR TITLE
Zynqmp new platforms

### PR DESCRIPTION
**Pull request by ierkiaga**
Add support in the build repository for the previously supported evaluation boards. The pull request includes a patch to the DTS overlay to ensure that kernel does not overwrite either ATF or OP-Tee specially in the ZCU104 and Ultra96 boards where DDR memory is more limited.

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Commit message: `zynqmp: reserve memory for ATF and OP-Tee`
s/ATF/TF-A/ and s/OP-Tee/OP-TEE/

**Review by etienne-lms — COMMENTED** [review]
LGTM but I don't know much about petalinux build env.

For commit "zynqmp: fix ITS warning messages", you could add an example of the warning in the commit message but it's not mandatory.

**Comment by ierkiaga** [comment]
> LGTM but I don't know much about petalinux build env.
> 
At this stage there is no reference to petalinux at all in the build directory, the only requirement for the build is just to download prebuilt firmware binaries from Xilinx/Avnet website.

> For commit "zynqmp: fix ITS warning messages", you could add an example of the warning in the commit message but it's not mandatory.
Will address that

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>` with comments addressed.
@ierkiaga, do you want this P-R and https://github.com/OP-TEE/optee_docs/pull/167 be merged into next 3.19.0 release tag?

**Comment by ierkiaga** [comment]
It would be nice to have it merged

**Review by etienne-lms — APPROVED** [review]

**Comment by jforissier** [comment]
@ierkiaga sure, thanks!

**Pull request merged**
