### PR TITLE
toolchain: update GCC to v11.3

### PR DESCRIPTION
**Pull request by jforissier**
Update to the Arm GCC toolchain version 11.3.rel1.

Signed-off-by: Jerome Forissier <jerome.forissier@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Tested on QEMUv8 with https://github.com/OP-TEE/optee_os/pull/5823.
On remaining issue to address before merging this:
```
$ xtest
[...]
pkcs11_1027 FAILED first error at pkcs11_1000.c:8692
```

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
> Tested on QEMUv8 with [OP-TEE/optee_os#5823](https://github.com/OP-TEE/optee_os/pull/5823). On remaining issue to address before merging this:
> 
> ```
> $ xtest
> [...]
> pkcs11_1027 FAILED first error at pkcs11_1000.c:8692
> ```

The test fails when the user is `test` but not when it is `root`. The failure is unrelated to GCC 11.3, it can be reproduced on master. CI doesn't fail on the master branch because it uses "make check" which [logs in as root](https://github.com/OP-TEE/build/blob/3.20.0/qemu-check.exp#L127).

@etienne-lms @MatthewSukyoung any idea how to fix that?

**Comment by jforissier** [comment]
Opened issue https://github.com/OP-TEE/optee_test/issues/649 for the PKCS#11 failure.

**Comment by TaihuLight** [comment]
@jforissier  Failed to build OP-TEE 3.21.0 for Hikey 960 with the updated GCC 11.3
#652 #https://github.com/OP-TEE/optee_os/issues/6060

**Pull request merged**
