### PR TITLE
Travis check

### PR DESCRIPTION
**Pull request by jforissier**
Some patches needed for https://github.com/OP-TEE/optee_os/pull/461.

### CODE REVIEW

**Comment by jforissier** [comment]
Rebased.

**Comment by jbech-linaro** [comment]
Quite a few small patches, might be worth squashing some of them. Anyhow, I leave it up to you to decide if you want to do that or not. The patches as such are looking good.

`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro agreed, I can squash into 2 or 3 commits.

**Comment by jforissier** [comment]
Squashed.

**Pull request merged**
