### PR TITLE
Move from arm-trusted-firmware to trusted-firmware-a

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by vchong** [comment]
Depends on https://github.com/OP-TEE/manifest/pull/144

**Comment by etienne-lms** [comment]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`

**Comment by jbech-linaro** [comment]
IBART is due to the manifest dependency, but this is LGTM.
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Tags added and ok to merge after https://github.com/OP-TEE/manifest/pull/144. Thanks!

**Pull request merged**
