### PR TITLE
ffa: Allow multiple SPs with same UUID

### PR DESCRIPTION
**Pull request by jellesels-arm**
Change the naming scheme of the SP binaries to make sure we can add multiple SPs with the same UUID to the system. Added the possibility to compile all TS SPs with the same FF-A UUID (protocol UUID).
This is need to support [5898](https://github.com/OP-TEE/optee_os/pull/5898)
This is a follow-up on [603](https://github.com/OP-TEE/build/pull/603)

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
In the commit message for "FF-A: Add test SPs to the fip package" you say:
_TF-A doesn't has a limited capacity_
I guess you mean:
_TF-A doesn't have an unlimited capacity_

For commit "FF-A: Add spm-test4 test sp" please use capital letters for SP
and also write SPs instead of sp's in the commit message.

For commit "TS: Use rpc protocol UUID", please use capital letters for RPC.

With that fixed:
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
> For commit "TS: Use rpc protocol UUID", please use capital letters for RPC.

...and aren't lowercase subsystem prefixes preferred? "ts:"

**Comment by jenswi-linaro** [comment]
> > For commit "TS: Use rpc protocol UUID", please use capital letters for RPC.
> 
> ...and aren't lowercase subsystem prefixes preferred? "ts:", "ff-a:" (or even "ffa:")

Yes, good point.

**Comment by jellesels-arm** [comment]
> > > For commit "TS: Use rpc protocol UUID", please use capital letters for RPC.
> > 
> > 
> > ...and aren't lowercase subsystem prefixes preferred? "ts:", "ff-a:" (or even "ffa:")
> 
> Yes, good point.

Done

**Pull request merged**
