### PR TITLE
Make include directive of toolchain.mk and  common.mk compulsory

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
@jforissier Is this worth merging?

**Comment by jbech-linaro** [comment]
I think it is used everywhere, so why not, but on the other hand has there been any issue with it as it is?

**Comment by vchong** [comment]
Not really, not unless someone (un)intentionally go and remove the included files and doesn't know what to do next. I suppose that's rare so we can probably drop this.

**Comment by jforissier** [comment]
Yeah, one way or the other is OK, really, but still, the version without "-" is more correct. So I don't mind merging this at all.
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Let's do the more correct thing then. ; )
Tag added. Thanks!

**Pull request merged**
