### PR TITLE
Create uboot.env from uboot.txt

### PR DESCRIPTION
**Pull request by igoropaniuk**
Add support for generation of uboot.env image from txt file

For default uboot.env.txt I've taken Joakim's version https://github.com/jbech-linaro/build/blob/c5c1c8e18020e4f869a01770238e24c2b3bb2db6/rpi3/firmware/uboot.env.txt
```
Fixes: https://github.com/OP-TEE/build/issues/85
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>
Tested-by: Igor Opaniuk <igor.opaniuk@linaro.org> (RPi3)
```

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
With last changes ...
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
@igoropaniuk if you squash and add the RB tag, then I can go on merging this.

**Comment by igoropaniuk** [comment]
@jbech-linaro done! thanks for reminding

**Pull request merged**
