### PR TITLE
Rewrite soc_term in Python

### PR DESCRIPTION
**Pull request by jforissier**
Rewriting `soc_term` in Python, as an alternative to #512.

### CODE REVIEW

**Comment by jforissier** [comment]
Something is wrong with IBART it seems... the tests look OK but the status is "Cancelled"
@jbech-linaro

**Comment by jenswi-linaro** [comment]
It seems that this script doesn't handle telnet commands (`-t` option to `soc_term`).

**Comment by jforissier** [comment]
> It seems that this script doesn't handle telnet commands (`-t` option to `soc_term`).

True, I could not find a use case for telnet codes in `build.git` so I decided to ignore them (legacy code I thought). I can add them if needed.

**Comment by jenswi-linaro** [comment]
Yes, please. I'm using it in my workflow with FVP.

**Comment by jforissier** [comment]
@jenswi-linaro I have added the `-t` option based on the C code, tested only with QEMU therefore without actual telnet codes to respond to. Can you check if it works for you?

**Comment by jenswi-linaro** [comment]
> @jenswi-linaro I have added the `-t` option based on the C code, tested only with QEMU therefore without actual telnet codes to respond to. Can you check if it works for you?

It seems it doesn't interpret the telnet codes. You can test for yourself with FVP if you put this script with the name `xterm` first in your `PATH`:
``` bash
#!/bin/sh


case "$2" in
*_0)
	local_port=54330
	;;
*_1)
	local_port=54331
	;;
*)
	echo "Unknown terminal name \"$2\""
	exit 1
esac

#echo socat TCP:$5:$6 EXEC:"telnet localhost $local_port"
#exec socat TCP:$5:$6 EXEC:"telnet localhost $local_port"

echo socat TCP:$5:$6 TCP:localhost:$local_port
exec socat TCP:$5:$6 TCP:localhost:$local_port
```

**Comment by jforissier** [comment]
@jenswi-linaro thanks for the test script. I think I fixed the remaining issue(s), can you please check again?

**Comment by jenswi-linaro** [comment]
Thanks @jforissier, it works now.
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by etienne-lms** [comment]
`Acked-by: Etienne Carriere <etienne.carriere@linaro.org>` for commit "Add soc_term.py"
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>` for commit "qemu, qemu_v8: use soc_term.py"

**Pull request merged**
