### PR TITLE
qemu_v8: Use -cpu max to support additional AArch64 features

### PR DESCRIPTION
**Pull request by ruchi393**
-cpu max provides support of maximum feature set available with
AArch64 architecture.This includes FEAT_PAuth and FEAT_BTI.

Signed-off-by: Ruchika Gupta <ruchika.gupta@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
You don't say why `sve=off`, is there some issue with it?

**Comment by ruchi393** [comment]
> You don't say why `sve=off`, is there some issue with it?

@jforissier , by default with cpu=max, sve gets enabled. With sve=on, linux fails to boot. I haven't debugged it. So explicitly marked sve as off.

**Comment by jforissier** [comment]
> > You don't say why `sve=off`, is there some issue with it?
> 
> @jforissier , by default with cpu=max, sve gets enabled. With sve=on, linux fails to boot. I haven't debugged it. So explicitly marked sve as off.

Alright, could you mention this in the commit description?

`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by ruchi393** [comment]
Tags applied and commit message updated. @jforissier , can you pull this in. Sorry for the delay.

**Comment by jforissier** [comment]
@ruchi393 no worries, thanks. Note: the IBART failure will go away when this branch is rebased.

**Pull request merged**
