### PR TITLE
qemu/qemu_v8: dependecy for make targets 'check'

### PR DESCRIPTION
**Pull request by etienne-lms**
Checking Qemu arguments expects the tool 'expect'.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
I don't understand the commit subject. If you see this line in a git log output, will you be able to tell that it's just the README.md that was changed?

**Comment by etienne-lms** [comment]
ok, I will rephrase.

**Comment by etienne-lms** [comment]
tag applied.

**Pull request merged**
