### PR TITLE
Fix build error with huge $PATH

### PR DESCRIPTION
**Pull request by etienne-lms**
Fix for Issue #597.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
> making the dependencies list being likely built twice

From my point of view, this looks like a degradation. I know this is an old fix, but it still looks strange to change random stuff until something reportedly works again. How is this problem reproduced upstream?

**Comment by jforissier** [comment]
I think a better option would be to generate one make target per TA, with the additional benefits that parallel build would be possible, and the first failure would stop the build.

**Comment by etienne-lms** [comment]
> > making the dependencies list being likely built twice
>
> From my point of view, this looks like a degradation. 

True, buiding twice some pieces is not nice, but build env find out nothing more needs to be done for those components and it does not affect overall build time. Yet, this part and the way I use a local shell variable to create the list to deps paths is not very clean.

I have not reproduced the inital issue.
@wamserma, do you confirm https://github.com/OP-TEE/build/issues/389 ris still affecting build environments?

**Comment by etienne-lms** [comment]
We have a nice _ta/Makefile_ here that knowns which TAs and order for build. We could use it, but it's scratched by CMake generated _Makefile_ file. Maybe rename the original one?

**Comment by jforissier** [comment]
> > I think a better option would be to generate one make target per TA ...
> 
> We have a nice _ta/Makefile_ **~here~ in _optee_test.git_** that knowns which TAs and order for build. We could use it, but it's scratched by CMake generated _Makefile_ file. Maybe rename the original one?
> 
> **(edited)**

Yes, I think we should do both. One rule per TA here, as well as use the TA Makefiles.

**Comment by wamserma** [comment]
> > > making the dependencies list being likely built twice
> > 
> > 
> > From my point of view, this looks like a degradation.
> 
> True, buiding twice some pieces is not nice, but build env find out nothing more needs to be done for those components and it does not affect overall build time. Yet, this part and the way I use a local shell variable to create the list to deps paths is not very clean.
> 
> I have not reproduced the inital issue. @wamserma, do you confirm #389 ris still affecting build environments?

I can confirm. I tried to set up a nice reproducible dev environment with Nix and ran into the issue. On a pure Ubuntu builds work as expected.
Drilling down into the Makefiles led to opening #597.

**Comment by etienne-lms** [comment]
@jforissier, I'm not shure I understand your suggestions.

> Yes, I think we should do both. One rule per TA here, 

Did you mean adding 1 buildroot make/install rule per TA implemented in the package,
in both _br-ext/.../optee_test_ext.mk_ and _optee_examples_ext.mk_ ?

> as well as use the TA Makefiles.

Buildroot recipe would invoke each TA _Makefile_ individually? or invoke a single _Makefile_ to make all repository TAs?

I think the buildroot recipe (or a yocto recipe) should run a single build that builds the package. We should not need to update a recipe because a TA was added in a optee repository and is embedded (unless there is specific configuration things needed in BR).
I would be in favor of renaming _ta/Makefile_ to _ta/make-install-tas.mk_ in optee_test and in optee_examples and have the buildroot recipe _optee_xxx_ext.mk_ to run a single `make -f make-install-tas.mk` or like command.

**Comment by jforissier** [comment]
I mean generate Makefile targets instead of generating a list of build commands:
```
A:
        make -C A/
all: A

B:
        make -C B/
all: B
```
...instead of:
```
all:
        ...
        make -C A/
        make -C B/
```

**Comment by etienne-lms** [comment]
With buildroot integration, we are expected to define 1 make variable named `OPTEE_TEST_EXT_POST_BUILD_HOOKS` to add commands to a build make target that is handled from buildroot env. We cannot add targets on a package make recipe in buildroot, like _package/foo/foo.mk_.
Same for installation.

**Comment by etienne-lms** [comment]
TA dev kit does not support CMake for now. We would need to launch a gnu make command from a CMake build env.

**Pull request closed without merging**
