### PR TITLE
MT8173 EVB support official kernel

### PR DESCRIPTION
**Pull request by jamescfkung**
Signed-off-by: James Kung <james.kung@linaro.org>
Tested-by: James Kung <james.kung@linaro.org> (MT8173 EVB)

### CODE REVIEW

**Comment by jamescfkung** [comment]
Using official Linux kernel v4.1-rc1 on MT8173 EVB
Related pull request: https://github.com/OP-TEE/manifest/pull/11

**Comment by pascal-brand-st-dev** [comment]
Reviewed-by: Pascal Brand <pascal.brand@linaro.org>

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jamescfkung** [comment]
Add "Reviewed-by" tags

**Pull request merged**
