### PR TITLE
stm32mp1: use FIP image format in TF-A and provision a partition for U-Boot env

### PR DESCRIPTION
**Pull request by etienne-lms**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro re. the IBART failure, I noticed:
```
  4344:  /home/optee/devel/qemu/out-br/build/busybox-1.34.1/scripts/gcc-version.sh: line 11: /home/optee/devel/qemu/out-br/per-package/busybox/host/bin/arm-linux-gnueabihf-gcc: No such file or directory
```
...could this be a missing dependency perhaps revealed by the [Buildroot parallel build](https://github.com/OP-TEE/build/commit/e9bff1c86e93820616e5283615d32683ac0c6d03) introduced not so long ago?

**Comment by jbech-linaro** [comment]
> ...could this be a missing dependency perhaps revealed by the [Buildroot parallel build](https://github.com/OP-TEE/build/commit/e9bff1c86e93820616e5283615d32683ac0c6d03) introduced not so long ago?

Perhaps, but not finding gcc looks weird. The overall toolchain(s) is pre-downloaded even before we start syncing the gits. I'm not 100% sure how Buildroot handles things under the hood. I thought we had configured it to use the locally installed copy of our toolchain instead of downloading it. Do you have any suggestion in mind how to address this issue?

**Comment by jbech-linaro** [comment]
I've added `BR2_PER_PACKAGE_DIRECTORIES=n` to both Hikey and QEMU. I've restarted the build for this PR.

**Comment by jbech-linaro** [comment]
Now we get other errors, this is from QEMU (Hikey passed without any errors).
```
 17655:  configure: WARNING: unrecognized options: --disable-gtk-doc, --disable-gtk-doc-html, --disable-doc, --disable-docs, --disable-documentation, --with-xmlto, --with-fop, --enable-ipv6, --disable-nls, --disable-static, --enable-shared
 17656:  Makefile:23: recipe for target '_all' failed
 17657:  make[1]: *** [_all] Error 2
 17658:  make[1]: Leaving directory '/home/optee/devel/qemu/out-br'
 17659:  common.mk:334: recipe for target 'buildroot' failed
 17660:  make: *** [buildroot] Error 2
```

**Comment by jbech-linaro** [comment]
> Have you `rm -rf out-br` since the last built? (I suppose you're not rebuilding from scratch each time?)

Yes, it always start from a clean "rm -rf'ed" folder.

**Comment by jbech-linaro** [comment]
I'll launch a build in the background here on my end on my own local computer to see if I can reproduce it.

**Comment by jbech-linaro** [comment]
> I'll launch a build in the background here on my end on my own local computer to see if I can reproduce it.

No issues seen on my local build, I used the same flags as on IBART. I'll retrigger the IBART build once more.

**Comment by jbech-linaro** [comment]
Seems "happy now", so I guess we're good to go. But I don't like this intermittent issues happening from time to time.

**Pull request merged**
