### PR TITLE
stm32mp1: define STM32MP15C-ED1

### PR DESCRIPTION
**Pull request by etienne-lms**
STM32MP15C-ED1 is the child board plugged on EV1 mother board. ED1 can
be used without its mother board with some interface restrictions
(I.e. no USB-C). This change defines the platform flavor. The several
components (optee_os, tf-a, u-boot, linux) already support ED1 DTS file
identifier.

Signed-off-by: Etienne Carriere <etienne.carriere@linaro.org>
Signed-off-by: Etienne Carriere <etienne.carriere@st.com>

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by etienne-lms** [comment]
tag applied. thanks.

**Comment by jforissier** [comment]
Does it make sense to take this in 3.13.0? It looks pretty safe to me, but on the other hand I suppose some support is needed in optee_os too?

**Comment by etienne-lms** [comment]
no other change is needed, ED1 is already supported but in this `build` repo.
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org>` in 3.13.0-rc1 + merged changes (optee_os/optee_test/linux/manifest/build)

**Pull request merged**
