### PR TITLE
toolchain: update GCC to v10.2

### PR DESCRIPTION
**Pull request by jbech-linaro**
Update the default GCC version to v10.2.

Fixes: https://github.com/OP-TEE/optee_os/issues/4233

Signed-off-by: Joakim Bech <joakim.bech@linaro.org>
Tested-by: Joakim Bech <joakim.bech@linaro.org> (QEMU v7, v8)

### CODE REVIEW

**Comment by jforissier** [comment]
`Acked-by: Jerome Forissier <jerome@forissier.org>`

**Comment by jbech-linaro** [comment]
Squashed, rebased and tag(s) applied (should be) ready for merge! Thanks! I have the 10.2 toolchain pre-downloaded to IBART, so once this has been merged, I'm gonna replace the 9.x one with this one (after that the first build will likely time-out, since it'll rebuild the `ccache`).

**Comment by jbech-linaro** [comment]
Hmm, hold off, commit message hasn't been updated. I'll check what happend.

**Comment by jbech-linaro** [comment]
> Hmm, hold off, commit message hasn't been updated. I'll check what happend.

Now it looks correct, I probably pushed from the wrong tree (tried on v7 as well as v8) ... ready for merge.

**Comment by jforissier** [comment]
> > Hmm, hold off, commit message hasn't been updated. I'll check what happend.
> 
> Now it looks correct, I probably pushed from the wrong tree (tried on v7 as well as v8) ... ready for merge.

Yes, all good, I see the once lost change in `br-ext/configs/toolchain-aarch64` is back, too :)

**Pull request merged**
