### PR TITLE
poplar: use buildroot for creating initial rootfs

### PR DESCRIPTION
**Pull request by igoropaniuk**
`Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>`

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
Tag applied, thanks

**Comment by igoropaniuk** [comment]
@jbech-linaro , I've added additional commit with different fixes.
Please confirm that I can apply your R-b tag to both.

Thanks!

**Comment by jbech-linaro** [comment]
> Please confirm that I can apply your R-b tag to both.

That is fine (maybe just add a sentence saying why you went down from 2 to 1).

**Comment by igoropaniuk** [comment]
> Please confirm that I can apply your R-b tag to both.

Added details to the commit message and attached tag. Thanks!

**Pull request merged**
