### PR TITLE
Switch to upstream arm tf

### PR DESCRIPTION
**Pull request by jenswi-linaro**

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/manifest/pull/71

**Comment by vchong** [comment]
Will this work if `CFG_WITH_PAGER=n` and `tee-pageable_v2.bin` is a 0 size file?

**Comment by jenswi-linaro** [comment]
Yes

**Comment by vchong** [comment]
Great. Thanks!

`Acked-by: Victor Chong <victor.chong@linaro.org>`

**Comment by jenswi-linaro** [comment]
Added patch for Juno also

**Comment by jforissier** [comment]
@vchong would you like to also ack the last patch since you looked at the other ones? Thanks.

**Comment by vchong** [comment]
@jforissier Sure. Ack for all 3 patches. Fyi this also tested ok on hikey* so will send out patches for those soon. Thanks.

**Comment by jenswi-linaro** [comment]
Tag applied.

**Pull request merged**
