### PR TITLE
Switch to upstream arm tf (op-tee header parsing) - hikey960

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Depends on:

https://github.com/ARM-software/arm-trusted-firmware/pull/1082 (this one might take a bit of time to show up on master!)
https://github.com/OP-TEE/build/pull/180

**Comment by vchong** [comment]
ARM-software/arm-trusted-firmware#1082 is now in master so please proceed with review.
Thanks!

**Comment by vchong** [comment]
ping

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Rebased and tag added. Thanks!

**Pull request merged**
