### PR TITLE
Use U-Boot on FVP

### PR DESCRIPTION
**Pull request by balint-dobszay-arm**
Depends on: https://github.com/OP-TEE/manifest/pull/278
Fixes: https://github.com/OP-TEE/optee_os/issues/5936

### CODE REVIEW

**Review by jforissier — APPROVED** [review]
- For commit "fvp: remove foundation platform":
  `Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`
- For commit "fvp: replace edk2+grub with u-boot":
  `Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by balint-dobszay-arm** [comment]
Thanks, tags applied

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by balint-dobszay-arm** [comment]
Thanks, tags applied

**Pull request merged**
