### PR TITLE
misc: remove driver modules from filesystem list

### PR DESCRIPTION
**Pull request by vchong**
optee.ko and optee_armtz.ko not required anymore with generic
driver

Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
If the driver is compiled as a loadable module then it needs to be included in the file list. The only drawback with having it there now is that you get a harmless but perhaps confusing error message.

**Comment by vchong** [comment]
Ah, ok. I will close this then. Thanks!

**Comment by jforissier** [comment]
It would be good to include the modules only when the driver is compiled as a module. We don't want confusing warning messages, do we?

**Comment by jenswi-linaro** [comment]
Agree, that would be the best.

**Comment by vchong** [comment]
Perhaps we can add an if statement to the makefiles to see if the .ko files are there and only include if yes?

**Comment by vchong** [comment]
Then again, there's no guarantee that everyone will use the same path to build the modules?

**Comment by jenswi-linaro** [comment]
If we can assume that they don't change the directory layout in the kernel tree it should be OK.

**Comment by vchong** [comment]
Ok. I'll submit a new PR with 'if' checks.

**Pull request closed without merging**
