### PR TITLE
Misc build fixes

### PR DESCRIPTION
**Pull request by jbech-linaro**
Fixes issues seen here:
https://travis-ci.org/OP-TEE/optee_os/builds/137444600#L195

And the build issue mentioned here:
https://github.com/OP-TEE/optee_os/issues/832

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
Tags applied, ready to be merged.

**Comment by jbech-linaro** [comment]
**Don't merge this**, the HiKey patch is wrong (noticed that when building on another computer).

**Comment by jbech-linaro** [comment]
So, now I've built everything locally and tested it on the actual device and with the Linux kernel patch mentioned in https://github.com/OP-TEE/optee_os/issues/832 all is OK. Regarding the kernel patch. I'll just grab that for now and put it on the kernel branch we're using. I also plan to reach out to Amit, since I think we can abandon our temporary branch and use his real RPB branch istead. But ... that's a side note.

Now ... ready to be merged.

**Pull request merged**
