### PR TITLE
qemu_v8: use ENABLE_SVE_FOR_NS=2 in TF_A_FLAGS

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Uses ENABLE_SVE_FOR_NS=2 in TF_A_FLAGS to let TF-A probe if SVE is enabled or not.

This should fix the CI timeout for Xen in https://github.com/OP-TEE/optee_os/pull/6169

### CODE REVIEW

**Comment by jforissier** [comment]
Let's try that :)
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jforissier** [comment]
There is a CI timeout for Rust, too. I don't know if it is caused by the TF-A changes or the upgrade to QEMU 8.0.0, though.

**Comment by jforissier** [comment]
> There is a CI timeout for Rust, too. I don't know if it is caused by the TF-A changes or the upgrade to QEMU 8.0.0, though.

TF-A definitely, because this PR with QEMU v8.0.0 + older TF-A (v2.6) + ENABLE_SME_FOR_NS=1 [build error otherwise] does work.

**Comment by jforissier** [comment]
It seems we need `ENABLE_SME_FOR_NS=2`.

> > There is a CI timeout for Rust, too. I don't know if it is caused by the TF-A changes or the upgrade to QEMU 8.0.0, though.
> 
> TF-A definitely, because this PR with QEMU v8.0.0 + older TF-A (v2.6) + ENABLE_SME_FOR_NS=1 [build error otherwise] does work. Exact same config with TF-A v2.9 times out.

It seems we need `ENABLE_SME_FOR_NS=2`.

**Comment by jenswi-linaro** [comment]
In a way, rust gets what it deserves. From my local build log:
```
 + curl https://sh.rustup.rs -sSf
+ sh -s -- -y --default-toolchain nightly-2021-09-20
info: downloading installer
error: could not amend shell profile: '/home/jens/.bash_profile': could not write rcfile file: '/home/jens/.bash_profile': Permission denied (os error 13)
```

**Comment by jforissier** [comment]
> In a way, rust gets what it deserves. From my local build log:
> 
> ```
>  + curl https://sh.rustup.rs -sSf
> + sh -s -- -y --default-toolchain nightly-2021-09-20
> info: downloading installer
> error: could not amend shell profile: '/home/jens/.bash_profile': could not write rcfile file: '/home/jens/.bash_profile': Permission denied (os error 13)
> ```

I did not get that error but maybe it is because I am not running from an old checkout? Also I don't have any `.bash_profile` in my home directory.

**Comment by jenswi-linaro** [comment]
I keep my RC files read-only because I don't want them changed behind my back.

Anyway, I'll add a commit with `ENABLE_SME_FOR_NS=2`.

**Comment by jforissier** [comment]
> I keep my RC files read-only because I don't want them changed behind my back.

Sounds like a good idea ;)
 
> Anyway, I'll add a commit with `ENABLE_SME_FOR_NS=2`.


Thanks!

**Comment by jforissier** [comment]
"qemu_v8: use ENABLE_SME_FOR_NS=2 in TF_A_FLAGS" is:

`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied.

**Pull request merged**
