### PR TITLE
Remove legacy toolchain

### PR DESCRIPTION
**Pull request by jbech-linaro**
This is a follow-up to the email thread with Ard about running newer toolchains with the GCC49 profile in UEFI.

I've done build testing on all platforms mentioned (and travis did build test for Juno). Then I have been running xtest on QEMU v8, FVP and RPi3 (which is about U-boot ...) all without regressions.

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
How about AOSP, isn't gcc 4.9 use there? Or that's still dealt with in a different way?

**Comment by jforissier** [comment]
Nice!
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jbech-linaro** [comment]
Squashed, rebased and tag(s) applied (should be) ready for merge! Thanks!

**Comment by jforissier** [comment]
I think those things are not needed now and should be removed:
https://github.com/OP-TEE/build/blob/master/common.mk#L115-L125
https://github.com/OP-TEE/build/blob/master/common.mk#L189-L193
https://github.com/OP-TEE/build/blob/master/br-ext/configs/toolchain-aarch32-legacy

@jenswi-linaro?

**Comment by jenswi-linaro** [comment]
https://github.com/OP-TEE/build/blob/master/common.mk#L115-L125 and
https://github.com/OP-TEE/build/blob/master/common.mk#L189-L193
should be cleaned up
https://github.com/OP-TEE/build/blob/master/br-ext/configs/toolchain-aarch32-legacy
can be removed

**Pull request merged**
