### PR TITLE
qemu kconfig: enable ION unmapped heap support

### PR DESCRIPTION
**Pull request by etienne-lms**
Latest changes in ION requires CONFIG_ION_UNMAPPED_HEAP to configure
the support for unmapped heap.

This configuration complies with current optee linux and plans for optee-next linux (v4.12).

### CODE REVIEW

**Comment by etienne-lms** [comment]
rebased on master.

**Comment by etienne-lms** [comment]
`Tested-by: Etienne Carriere <etienne.carriere@linaro.org> (qemu_virt, qemu_armv8)`

**Comment by jbech-linaro** [comment]
Is it the same patch we need to the HiKey issues seen on Travis? If yes, could you please add one more commit for HiKey for this patch set? Other than that ...
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by etienne-lms** [comment]
Ok, i will add another commit for the hikey kernel config.

**Comment by etienne-lms** [comment]
@jbech-linaro, I applied your r-b tag to both commits...

**Pull request merged**
