### PR TITLE
Unused targets

### PR DESCRIPTION
**Pull request by jforissier**
Remove unused stuff in makefiles.

### CODE REVIEW

**Comment by jforissier** [comment]
Hmmm I see references to OPTEE_CLIENT_EXPORT here:
```
zynqmp/optee-test/optee-test.bb:OPTEE_CLIENT_EXPORT = "${TMPDIR}/deploy/images/${MACHINE}/optee/export_client"
zynqmp/optee-test/optee-test.bb:EXTRA_OEMAKE_append = " OPTEE_CLIENT_EXPORT=${OPTEE_CLIENT_EXPORT}"
```

Would this PR break the ZynqMP build?

**Review by etienne-lms — COMMENTED** [review]
~~`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`~~
(edited: let's wait for the whole cleanup)

**Comment by etienne-lms** [comment]
I boud zynqmp/optee-test/optee-test.bb relies on OP-TEE/build.git

**Comment by jforissier** [comment]
> I doubt zynqmp/optee-test/optee-test.bb relies on OP-TEE/build.git

I hope you're right. @mimok / @sephalon could you please confirm? (since you are the authors of the two commits that touch `zynqmp/optee-test/optee-test.bb`).

**Comment by jforissier** [comment]
@etienne-lms  updated with a few more things removed.

**Review by etienne-lms — COMMENTED** [review]
`Reviewed-by: Etienne Carriere <etienne.carriere@linaro.org>`
(if really think zynqmp is safe, the recipes hosted do not fetch our build.git and very unlikely petalinux rely on it)

**Comment by mimok** [comment]
As far as I remember, zynqmp target does not rely on other files in OPTEE/build.git. Your PR should not break it.

**Comment by jforissier** [comment]
@mimok that's good news, thanks!

**Pull request merged**
