### PR TITLE
rpi3: use firmware fetched by repo

### PR DESCRIPTION
**Pull request by igoropaniuk**
Helps to avoid cases with broken rpi3 firmware archive, which happens
when build process was interrupted or because of network issues.

Relates: https://github.com/OP-TEE/manifest/pull/75
```
Reported-by: Bjorn Wennberg <bjorn.wennberg@forgerock.com>
Signed-off-by: Igor Opaniuk <igor.opaniuk@linaro.org>
```

### CODE REVIEW

**Comment by igoropaniuk** [comment]
@jbech-linaro this is a possible fix for the issue, which Bjorn mentioned about

**Comment by jbech-linaro** [comment]
I think this is a good change, I supposed you have tested it with the manifest in OP-TEE/manifest#75 locally?
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by igoropaniuk** [comment]
@jbech-linaro, now everything is fine (found one issue), could you please check my comment https://github.com/OP-TEE/manifest/pull/75#issuecomment-329719076 and reaffirm that I can still apply your R-b tags. Thanks!

**Comment by igoropaniuk** [comment]
Tag applied and rebased, thanks!

PR is ready for merge

**Pull request merged**
