### PR TITLE
Add hikey960 doc and update hikey doc

### PR DESCRIPTION
**Pull request by vchong**

### CODE REVIEW

**Comment by jforissier** [comment]
Since you're updating `hikey.md`: I think there is a mistake in https://github.com/OP-TEE/build/blob/master/docs/hikey.md#3-supported-hikey-boards. Where does the "Kirin 620" name come from? To the best of my knowledge, this is the name of the SoC, not the board. The board is still "HiKey". So I would suggest to remove the first column.
Also in the same table, it might be useful to add "Green solder mask" and "Black solder mask" in the comments (CircuitCo boards are green, LeMaker ones are black -- well as far as I know!).

**Comment by vchong** [comment]
`hikey.md` updated per comment.

**Comment by jforissier** [comment]
Thanks. 
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by vchong** [comment]
Squashed and tag added. Thanks!

**Pull request merged**
