### PR TITLE
fvp: Add libpsats support

### PR DESCRIPTION
**Pull request by gabor-toth-arm**
TS introduced a new shared library to help userspace applications integrate PSA clients. To avoid building this library multiple times add a dedicated build step, and share the resulting binary with all dependees.

### CODE REVIEW

**Review by jforissier — COMMENTED** [review]
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by gabor-toth-arm** [comment]
Hi @jenswi-linaro !

Could you merge this small change?

**Comment by jenswi-linaro** [comment]
Done!

**Pull request merged**
