### PR TITLE
optee_examples_ext.mk, optee_test_ext.mk: add host-python3-cryptography

### PR DESCRIPTION
**Pull request by hoiho-amzn**
Add dependency on python3-cryptography to prepare to migrate away from
Cryptodome

Signed-off-by: Donald Chan <hoiho@lab126.com>

### CODE REVIEW

**Comment by hoiho-amzn** [comment]
This PR is needed to prepare for https://github.com/OP-TEE/optee_os/issues/4599

**Comment by jenswi-linaro** [comment]
> Add dependency on python3-cryptography to prepare to migrate away from Cryptodome

Does this mean that we eventually can remove Cryptodome once the migration is complete or will we end up stuck with both?

**Comment by hoiho-amzn** [comment]
Once we migrated the Python script, we can remove this Cryptodome dependency.

**Comment by jenswi-linaro** [comment]
> Once we migrated the Python script, we can remove this Cryptodome dependency.

Do you intend to migrate all the python scripts too?

**Comment by hoiho-amzn** [comment]
> Do you intend to migrate all the python scripts too?

Intention is just to migrate `sign_encrypt.py` and `pem_to_pub_c.py` from Cryptodome to pyca/cryptography.

**Comment by jenswi-linaro** [comment]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by hoiho-amzn** [comment]
Hi @jforissier, unfortunately it is not possible....I will list the sequence here:

1. This PR is merged
2. Another PR is submitted to buildroot to use the `host-python3-cryptography` when building `optee-os`
3. Once the PR in step 2 goes to an official buildroot release, bump its versions across https://github.com/OP-TEE/manifest
4. Then submit the PR to migrate the signing script to use `pyca/cryptography`
5. Remove all the `host-python3-pycryptodomex` dependencies finally.

**Comment by jforissier** [comment]
@hoiho-amzn now that https://github.com/OP-TEE/build/pull/533 is merged we can close this, the `host-python3-pycryptodomex` can be removed at a later time. Thanks for your contributions.

**Pull request closed without merging**
