### PR TITLE
Update toolchain.mk

### PR DESCRIPTION
**Pull request by JohnyDev42**
This option is required for insecure connection

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
I think this is OK, but then we should check that the sha1sums of downloaded binaries matches expected values. We should check the sha1sums regardless of this switch though.

**Comment by ArunSahu42** [comment]
Is threre any way to check the sha1sums of the downloaded binaries

**Comment by jbech-linaro** [comment]
Right, that seems to be what @ryankumar is facing in https://github.com/OP-TEE/optee_os/issues/2521. But I think what Jens mentioned is that if we introduce the `-k`, then we should check that that downloaded toolchain is what we expect, so in psuedo code you do:
```c
toolchain_sha256sum = "abababababababab...." # this is pre-calculated and hardcoded in here
curl ... toolchain.xz
if (sha256sum(toolchain.xz) != toolchain_sha256sum)
    print ("Toolchain hash mismatch")
    return error
```
Something like that is what should be done in `toolchain.mk`.

**Comment by ArunSahu42** [comment]
I am not getting why this sha256sum is required...if I will download this toolchain insecurely does it effect my sha256sum and why ?

**Comment by jenswi-linaro** [comment]
Man in the middle...

**Comment by wamserma** [comment]
Hm, I think this PR could be closed w/o merging.

**Comment by jbech-linaro** [comment]
> Hm, I think this PR could be closed w/o merging.

Agree and we haven't seen anyone having this issue for quite some time now. If a reader of this still think this is an issue, then please open the ticket again. I'm closing it for now. Thanks!

**Pull request closed without merging**
