### PR TITLE
hikey: Use mtools to avoid sudo during build

### PR DESCRIPTION
**Pull request by d3zd3z**
Instead of using sudo/mount to build the FAT image, use commands from
the mtools package to copy files into the FAT image.  This eliminates
the requirement to use sudo during the build.  It also removes a small
sleep necessary to make umount work.

Signed-off-by: David Brown <david.brown@linaro.org>

### CODE REVIEW

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
Nice!
`Reviewed-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jbech-linaro** [comment]
I tried this and was first surprised that it still asked for sudo. But after looking at what's happening I found another Makefile that uses sudo. I'm not sure whether the same tricks can be applied to that [Makefile](https://github.com/96boards/l-loader/blob/master/Makefile#L18) in l-loader?.

Anyhow, this particular patch works, so I'll go a head and merge it.

**Comment by d3zd3z** [comment]
The l-loader sudo is even easier, just remove it. As long as you don't have root-owned files sitting around, it will build just fine without the sudo.

**Comment by jforissier** [comment]
@d3zd3z good suggestion, works fine here too without sudo. I've created https://github.com/96boards/l-loader/pull/12.

**Comment by jbech-linaro** [comment]
Thanks @jforissier !

**Pull request merged**
