### PR TITLE
Xen FF-A mediator

### PR DESCRIPTION
**Pull request by jenswi-linaro**
This can be tested with:
```
repo init -u https://github.com/jenswi-linaro/manifest.git -m qemu_v8.xml -b xen_ffa
repo sync -j8
cd build
make toolchains -j2
make XEN_BOOT=y SPMC_AT_EL=1 all -j8
make XEN_BOOT=y SPMC_AT_EL=1 run-only
```

This depends on:
- https://github.com/OP-TEE/optee_os/pull/5359
- https://review.trustedfirmware.org/c/TF-A/trusted-firmware-a/+/15339
- Xen patches in this PR, to be updated as https://lists.xenproject.org/archives/html/xen-devel/2022-06/msg00281.html progress
- Linux v5.19-rc1 with a FF-A fix

### CODE REVIEW

**Comment by jforissier** [comment]
I just give this a quick test, Dom0 worked fine (xtest passed) but I couldn't start DomU:

```
# domu
cd /mnt/host/build/qemu_v8/xen
xl create guest.cfg
Parsing config from guest.cfg
libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Invalid argument
libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
```

Also there are quite a few debug messages (the first one appears a lot), are they useful?
```
D/TC:1 0 ffa_inactivate:526 cookie 0x100000010005

D/TC:? 0 thread_rpc_free:1501 freeing cookie 0x100000010005

D/TC:1 0 mobj_ffa_get_by_cookie:401 cookie 0x100000010000 active: refc 2
```

**Comment by jenswi-linaro** [comment]
> I just give this a quick test, Dom0 worked fine (xtest passed) but I couldn't start DomU:
> 
> ```
> # domu
> cd /mnt/host/build/qemu_v8/xen
> xl create guest.cfg
> Parsing config from guest.cfg
> libxl: error: libxl_create.c:671:libxl__domain_make: domain creation fail: Invalid argument
> libxl: error: libxl_create.c:1233:initiate_domain_create: cannot make domain: -3
> ```

I probably missed adding some patch when updating for the last patchset. I'll try to backport the next patchset to get this to work again.

> 
> Also there are quite a few debug messages (the first one appears a lot), are they useful?
> 
> ```
> D/TC:1 0 ffa_inactivate:526 cookie 0x100000010005
> 
> D/TC:? 0 thread_rpc_free:1501 freeing cookie 0x100000010005
> 
> D/TC:1 0 mobj_ffa_get_by_cookie:401 cookie 0x100000010000 active: refc 2
> ```

These are still quite useful for me. It makes it easy to check for shared memory leakage. The last print is quite interesting `refc 2` means that this shared memory object is already used by another thread so this is probably a shared page with multiple argument structs inside. The `1` in the middle means that it belongs to the first guest, the second guest will have a `2` instead. You can also tell from the cookie who has assigned the value, if done by Xen it will have different high bits (I can't recall at the moment which value is used though).

We should remove these at some point.

**Comment by balint-dobszay-arm** [comment]
Hi Jens, now that the FF-A mediator patches have been merged to Xen, do you plan to continue this PR? Thanks

**Comment by jenswi-linaro** [comment]
Good point, I'll open this for now as a reminder.

**Comment by jenswi-linaro** [comment]
Xen is at `4.18.0-rc5` now, I'll resume this work when `4.18.0` is out.

**Comment by jenswi-linaro** [comment]
This was replaced by https://github.com/OP-TEE/build/pull/702/

**Pull request closed without merging**
