### PR TITLE
rpi3.md: Link to latest Linaro Debian rootfs

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
Have you tried it?
`Acked-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
@jbech-linaro I don't have an rpi3 board :s, but Marwen from LDTS 2169 did. In any case, this PR always link to the latest build, not a fixed version, so it will change anyway over time. If you think that's too risky or might be unstable, we can change/drop this.

**Comment by jbech-linaro** [comment]
This is fine, let's merge it.

**Comment by vchong** [comment]
Ok. Tag added. Thanks!

**Pull request merged**
