### PR TITLE
benchmark: drop support for benchmark framework

### PR DESCRIPTION
**Pull request by igoropaniuk**
Drop Benchmark Framework as current implementation is non-function and obsolete, and it's not supported anymore.

### CODE REVIEW

**Comment by igoropaniuk** [comment]
depends on https://github.com/OP-TEE/optee_os/pull/6611 and https://github.com/OP-TEE/optee_client/pull/373

**Review by jenswi-linaro — COMMENTED** [review]
`Acked-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by igoropaniuk** [comment]
@jenswi-linaro tag applied and rebased. thanks!

**Review by etienne-lms — COMMENTED** [review]
`Acked-by: Etienne Carriere <etienne.carriere@foss.st.com>`

**Comment by igoropaniuk** [comment]
@etienne-lms tag applied

**Pull request merged**
