### PR TITLE
docs: Add libssl-dev to prerequisites

### PR DESCRIPTION
**Pull request by jenswi-linaro**
Signed-off-by: Jens Wiklander <jens.wiklander@linaro.org>

### CODE REVIEW

**Comment by jforissier** [comment]
Might be useful to say why it's needed in the commit log. Anyway, I trust you ;)
`Acked-by: Jerome Forissier <jerome.forissier@linaro.org>`

**Comment by jenswi-linaro** [comment]
Tag applied, commit message updated.

**Comment by jforissier** [comment]
Needs rebasing.

**Comment by jenswi-linaro** [comment]
Rebased

**Pull request merged**
