### PR TITLE
Add driver to filesystem only if built as module.

### PR DESCRIPTION
**Pull request by vchong**
Signed-off-by: Victor Chong <victor.chong@linaro.org>

### CODE REVIEW

**Comment by vchong** [comment]
Replaces #58

**Comment by pascal-brand-st-dev** [comment]
`Reviewed-by: Pascal Brand <pascal.brand@linaro.org>`

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by vchong** [comment]
Tags added and ready for merge.
Thanks!

**Comment by jbech-linaro** [comment]
@vchong @pascal-brand-st-dev have you seen this?

I think we have an issue here, that we missed on the review also. Without my fix below, I get the following error:
```bash
/bin/sh: 1: Syntax error: ";" unexpected
make: *** [filelist-tee] Error 2
```

The following patch fixes that. So I guess that will be needed on all targets where we added this.

```patch
diff --git a/qemu.mk b/qemu.mk
index 62f2f92..6797b6d 100644
--- a/qemu.mk
+++ b/qemu.mk
@@ -136,12 +136,12 @@ filelist-tee: xtest
 	@echo "# Secure storage dig" >> $(GEN_ROOTFS_FILELIST)
 	@echo "dir /data 755 0 0" >> $(GEN_ROOTFS_FILELIST)
 	@echo "dir /data/tee 755 0 0" >> $(GEN_ROOTFS_FILELIST)
-	@if [ -e $(OPTEE_GENDRV_MODULE) ]; then
-		@echo "# OP-TEE device" >> $(GEN_ROOTFS_FILELIST)
-		@echo "dir /lib/modules 755 0 0" >> $(GEN_ROOTFS_FILELIST)
-		@echo "dir /lib/modules/$(call KERNEL_VERSION) 755 0 0" >> $(GEN_ROOTFS_FILELIST)
-		@echo "file /lib/modules/$(call KERNEL_VERSION)/optee.ko $(OPTEE_GENDRV_MODULE) 755 0 0" >> $(GEN_ROOTFS_FILELIST)
-	@fi
+	@if [ -e $(OPTEE_GENDRV_MODULE) ]; then \
+		@echo "# OP-TEE device" >> $(GEN_ROOTFS_FILELIST) \
+		@echo "dir /lib/modules 755 0 0" >> $(GEN_ROOTFS_FILELIST) \
+		@echo "dir /lib/modules/$(call KERNEL_VERSION) 755 0 0" >> $(GEN_ROOTFS_FILELIST) \
+		@echo "file /lib/modules/$(call KERNEL_VERSION)/optee.ko $(OPTEE_GENDRV_MODULE) 755 0 0" >> $(GEN_ROOTFS_FILELIST) \
+	;fi
 	@echo "# OP-TEE Client" >> $(GEN_ROOTFS_FILELIST)
 	@echo "file /bin/tee-supplicant $(OPTEE_CLIENT_EXPORT)/bin/tee-supplicant 755 0 0" >> $(GEN_ROOTFS_FILELIST)
 	@echo "dir /lib/arm-linux-gnueabihf 755 0 0" >> $(GEN_ROOTFS_FILELIST)
```

**Comment by vchong** [comment]
Sorry, I missed that. Will send it a fix asap.

**Comment by jforissier** [comment]
I think you need to use `echo` not `@echo` inside the `if` statement. You also need a `;` at the end of each line otherwise it will not pront what you expect ;)

**Comment by vchong** [comment]
@jforissier Thanks! I was in the middle of testing that as well.
Submitted #63.
Again, sorry for missing the bug.

**Pull request merged**
