### PR TITLE
Remove modprobe optee_armtz in case of generic driver

### PR DESCRIPTION
**Pull request by pascal-brand-st-dev**
Signed-off-by: Pascal Brand <pascal.brand@st.com>

### CODE REVIEW

**Comment by jbech-linaro** [comment]
`Reviewed-by: Joakim Bech <joakim.bech@linaro.org>`

**Comment by jforissier** [comment]
If this change is merged it means we can't use the "old" driver anymore? Should this be conditional instead?

**Comment by jbech-linaro** [comment]
@jforissier , please note the branch that Pascal is trying to merge to (it's not the official master branch which still uses the old driver).

**Comment by jenswi-linaro** [comment]
`Reviewed-by: Jens Wiklander <jens.wiklander@linaro.org>`

**Comment by jforissier** [comment]
@jbech-linaro sorry I did not notice. Looks good then!

**Pull request merged**
